### ISSUE TITLE
docs/examples/dowell_chmerge_pdf.ipynb does not run

### ISSUE THREAD

**Issue by petr-lanl** [ColwynGulliford/distgen#15]
Running Distgen examples. dowell_chmerge_pdf complains about `ModuleNotFoundError: No module named 'distgen.ds_cathode_model'`

![image](https://github.com/ColwynGulliford/distgen/assets/67295521/2e09a165-b537-431f-9cde-64d298c5a563)

I can see that the file is present on github but not in my conda installation. Distgen was installed by lume-gpt via conda-forge channel.

After some examination, I can see that distgen on conda-forge was updated on August 1st while I am trying more recent things available on github only.

**Comment by ColwynGulliford** [comment]
Hi Petr,

This doesn't run because that feature has not been included in the official release of Distgen yet - so the conda version does not contain that cathode model.  

I'm hoping to release a new version by tomorrow with the model included.
