### ISSUE TITLE
How to use distgen to generate two different particle beams distributions?

### ISSUE THREAD

**Issue by snwdiphone1994** [ColwynGulliford/distgen#4]
Recently we had a problem with distgen：How to use distgen to generate two different particle beams（Different time distributions, different space distributions, different momentum distributions）?
Is it possible to make some changes in the YAML input file?

**Comment by ColwynGulliford** [comment]
In general there are two ways to combine beams.  The simplest is to generate two beams and add them together.  This is detailed in the basics.ipynb that you can get from the examples folder in the repo:

https://github.com/ColwynGulliford/distgen/blob/master/examples/basic.ipynb

Create the first beam and save it to a ParticleGroup object:
<img width="669" alt="Screen Shot 2021-04-15 at 9 46 02 AM" src="https://user-images.githubusercontent.com/36416205/114879665-66989980-9dcf-11eb-8709-6d83c92517de.png">

Create a second beam:
<img width="681" alt="Screen Shot 2021-04-15 at 9 39 47 AM" src="https://user-images.githubusercontent.com/36416205/114878717-87142400-9dce-11eb-9c3f-808ea400f5db.png">

And add them together:
<img width="418" alt="Screen Shot 2021-04-15 at 9 40 43 AM" src="https://user-images.githubusercontent.com/36416205/114878852-a8751000-9dce-11eb-8512-95ffaae4c848.png">

The resulting particle group can be used to access the combined beam.  Please see the OpenPMD-beamphysics repository for details on how to output the particles to input files for various beam codes:
https://github.com/ChristopherMayes/openPMD-beamphysics

You can also use the particle group to write your own particles to file.  Coordinates are accessed like this:
x_coordinates = pg['x]

Does this solve your problem?  The other way to combine beams is to use the superposition operator, which is described in the example_dists notebook.

**Comment by ColwynGulliford** [comment]
If that does not solve things, could you describe the beam you are trying to create?

**Comment by snwdiphone1994** [comment]
@ColwynGulliford

   Thank you very much for your reply. The fact that the different ParticleGroup objects can be added directly is very useful.

   In the attached file, we want to set px = py =0 and import PDF in pz800.1d.txt to set the distribution of pz.

pz_dist:
   file: pz800.1d.txt
   type: file1d
   units: eV/c
![image](https://user-images.githubusercontent.com/57423619/115170472-55170080-a0f3-11eb-97d9-b8ed5c51d8b0.png)
![image](https://user-images.githubusercontent.com/57423619/115170542-7bd53700-a0f3-11eb-830b-35e350a4bc8e.png)

But the program finally calculates the distribution of pz(as shown in Fig.1) which is not what we want((as shown in Fig.2)).Thanks for the feedback.
Fig1
![1](https://user-images.githubusercontent.com/57423619/115170222-ad99ce00-a0f2-11eb-8efa-e15c9ad9b639.jpeg)
Fig2
![2](https://user-images.githubusercontent.com/57423619/115170239-b8546300-a0f2-11eb-9583-f6c9c63c281b.jpeg)

**Comment by ColwynGulliford** [comment]
Here is an example that I believe does what you want:

n_particle: 20000
output:
  file: example.out.txt
  type: gpt
pz_dist:
  file: cutgauss.pz.txt
  type: file1d
  units: eV/c
random_type: hammersley
start:
  tstart:
    units: sec
    value: 0
  type: time
total_charge:
  units: pC
  value: 10
  
Where the file "cutlass.pz.txt" stores the same pz PDF you sent (I believe this comes from the distgen examples/data folder).  Running the above yaml file gives:

<img width="818" alt="Screen Shot 2021-04-18 at 10 19 22 PM" src="https://user-images.githubusercontent.com/36416205/115172889-2453ae80-a094-11eb-8489-ab8fbd3690ed.png">

which looks like your figure (1).  One thing to be careful with is the "start" type used in the main yaml input file.  If you use cathode, then distgen assumes a Gaussian distribution for the px, py, pz.  In your example you want to have a non-Gaussian pz PDF, so make sure to have start:type: time (time start).  When creating a bunch at a given time, the code does not assume a particle emission model from a cathode, and gives you full control over px, py, pz.

Thanks for you submission.  Please let me know if you have any further questions.

**Comment by snwdiphone1994** [comment]
@ColwynGulliford
![image](https://user-images.githubusercontent.com/57423619/115188046-e5b30800-a116-11eb-975e-05f8ae3abd66.png)

If I set start:type: time, then I  can not specified t distribution for time start.
If I set start:type: cathode, then I  can not specified Px,Py,Pz distributions.
So is there a way to customize the time distribution (Gaussian)  and momentum distributions (cutgauss.pz.txt)?
Thanks again for your reply

**Comment by ColwynGulliford** [comment]
I've added a feature that let's you remove the 'start' key from the input yaml file, and in that mode it will allow you to set: x, y, z, px, py, pz, t, however you like.

Here is an input file that set's pz and t (Gaussian):

n_particle: 20000
output:
  file: example.out.txt
  type: gpt
pz_dist:
  file: cutgauss.pz.txt
  type: file1d
  units: eV/c
t_dist:
  type: g
  sigma_t: 
    value: 10
    units: ps
random_type: hammersley
total_charge:
  units: pC
  value: 10
  
<img width="1017" alt="Screen Shot 2021-04-19 at 10 19 52 AM" src="https://user-images.githubusercontent.com/36416205/115251717-cb6a3180-a0f8-11eb-9729-3fdeef771878.png">
<img width="432" alt="Screen Shot 2021-04-19 at 10 20 12 AM" src="https://user-images.githubusercontent.com/36416205/115251808-e472e280-a0f8-11eb-807c-88ee12373f06.png">

These changes have been pushed to the repo.  Are you using Conda to install the package?  If so I can issue a new release.

**Comment by snwdiphone1994** [comment]
@ColwynGulliford ,Thank you for spending so much time and energy to solve my confusion. The problem has been well solved

**Comment by ColwynGulliford** [comment]
Thanks you for using the code, I'm happy to help.
